'use client';

import { Landing, type LandingContent } from "../page";

const CTA_PRIMARY = "https://www.paypal.com/donate";
const CTA_REPORT = "https://example.com/angels-haven-transparency.pdf";
const CTA_COMMUNITY = "https://www.facebook.com/groups/480707493946285";

const TR_CONTENT: LandingContent = {
  hero: {
    eyebrow: "Canlı kurtarma görevi • Heathrow uçuşu",
    headline: "Bu gece bir canı uçağa bindiren kişi sen ol.",
    subheadline: "Heathrow hattına hazır yedi dostumuz var. £1 mama ve ilaçları, £120 charter açığını kapatır.",
    summary: "Charity Commission #1204821 • DEFRA lisanslı koridor • Dakikalar içinde WhatsApp güncellemeleri",
    highlights: [
      "Canlı geri sayımı izle, kasalar dolarken gör.",
      "Nova, Argo, Lale ve pistte bekleyen diğer patilerle tanış.",
      "Gönderdiğin her sterlin makbuz, vet notu ve varış videosuyla sana geliyor.",
    ],
    facesCaption: "Nova, Argo ve Lale pistte hazır—son faturayı sen kapat, uçuş açılsın.",
    ctaLabel: "Uçuşu başlat",
    ctaHref: "#adopt",
    donateHref: CTA_PRIMARY,
    donateAmounts: [8, 25, 60, 120],
    defaultSelectionLabel: "Göreve güç kat",
    donationStories: [
      { amount: 8, label: "3 kap iyileştirme maması" },
      { amount: 25, label: "Bir patinin ihracat evrağı" },
      { amount: 60, label: "DEFRA kasasını üçe paylaştırır" },
      { amount: 120, label: "Bu geceki charter koltuğu" },
    ],
    stats: {
      label: "Bu ay güvenli eve ulaşan",
      value: 18,
      suffix: "",
    },
    quickActions: [
      {
        id: "sponsor-crate",
        label: "Kasayı sponsorla",
        caption: "£60 DEFRA kasasını üç kişiyle paylaştırır",
        href: CTA_PRIMARY,
        icon: "sponsor",
      },
      {
        id: "adopt-pack",
        label: "Uçuş ekibini gör",
        caption: "Sahiplenme dosyalarını aç",
        href: "#adopt",
        icon: "adopt",
      },
      {
        id: "escort-flight",
        label: "Uçuşa refakat et",
        caption: "Bir sonraki Heathrow teslimine katıl",
        href: "mailto:hello@angelshaven.org?subject=U%C3%A7u%C5%9F%20refakat%C3%A7isi",
        icon: "visit",
      },
      {
        id: "join-briefing",
        label: "Görev brifingine katıl",
        caption: "14,6 bin gönüllü canlı operasyonda",
        href: CTA_COMMUNITY,
        icon: "community",
      },
    ],
    trustMarks: [
      { id: "charity", label: "Charity Commission", caption: "No. 1204821", href: "https://register-of-charities.charitycommission.gov.uk/charity-details/?regid=1204821" },
      { id: "wired", label: "WIRED Impact", caption: "2024 şeffaflık listesi", href: "https://www.wired.co.uk" },
      { id: "defra", label: "DEFRA Taşıma", caption: "Lisanslı kurtarma koridoru", href: "https://www.gov.uk/government/organisations/department-for-environment-food-rural-affairs" },
    ],
    media: {
      poster: "/images/hero-poster.avif",
      video: "/videos/hero-pack.mp4",
      alt: "Kurtarılan köpekler çimlerde koşarken",
    },
    liveCounter: {
      label: "Bu hafta başvuran aile",
      initial: 64,
      minIncrement: 1,
      maxIncrement: 3,
      intervalMs: 7200,
      suffix: "aile",
    },
    socialProof: [
      {
        id: "homecomings",
        metric: "🏡 6 mutlu ev",
        caption: "son 48 saatte",
        media: {
          poster: "/images/story-mila.avif",
          video: "/videos/community-loop.mp4",
          alt: "Yeni ailesiyle buluşan köpekler",
        },
      },
      { id: "group", metric: "👥 14,6 bin gönüllü", caption: "Facebook görev merkezinde canlı" },
      { id: "audit", metric: "Denetim tamam", caption: "Paws & Claws LLP FY23 güvencesi" },
    ],
    urgency: {
      remainingLabel: "Uçuşa hazır pati",
      remainingValue: "7",
      goalLabel: "Uçuş fonu %73",
      goalPercent: 73,
      footer: "Pazar gecesi charter açılmadan son vet imzalarını birlikte tamamlayalım.",
    },
    recurringHint: "Aylık melek ol, koridor her hafta sonu açık kalsın.",
    ticker: {
      headline: "Canlı bağış akışı",
      entries: [
        { id: "ayse-lon", name: "Ayşe K.", amount: 25, city: "Londra, UK", minutesAgo: 4, method: "Apple Pay" },
        { id: "murat-izm", name: "Murat S.", amount: 8, city: "İzmir, TR", minutesAgo: 7, method: "Stripe" },
        { id: "ella-man", name: "Ella R.", amount: 50, city: "Manchester, UK", minutesAgo: 10, method: "PayPal" },
        { id: "deniz-ank", name: "Deniz A.", amount: 12, city: "Ankara, TR", minutesAgo: 13, method: "Visa" },
        { id: "cihan-ist", name: "Cihan D.", amount: 8, city: "İstanbul, TR", minutesAgo: 19, method: "Apple Pay" },
        { id: "olivia-brt", name: "Olivia P.", amount: 100, city: "Bristol, UK", minutesAgo: 26, method: "Havale" },
      ],
    },
  },
  usp: [
    "Satın alma, sahiplen",
    "Uçuşa hazır ekip",
    "Aylık şeffaflık",
    "Tek dokunuş sponsor",
  ],
  steps: [
    {
      id: "choose",
      badge: "Adım 01",
      title: "Tutarını seç",
      copy: "£1 ile başla ya da istediğin tutarı gir. Canlı sayaç bağışınla birlikte anında güncellenir.",
      media: {
        poster: "/images/step-choose.avif",
        video: "/videos/step-choose.mp4",
        alt: "Bağış seçici arayüzü",
      },
    },
    {
      id: "pay",
      badge: "Adım 02",
      title: "Güvenle öde",
      copy: "Apple Pay, Google Pay, Stripe ve PayPal tek sayfada birleşir—hesap açmadan bağışı tamamlarsın.",
      media: {
        poster: "/images/step-pay.avif",
        video: "/videos/step-pay.mp4",
        alt: "Ödeme onay ekranı",
      },
    },
    {
      id: "impact",
      badge: "Adım 03",
      title: "Etkini izle",
      copy: "Günlük videolar, veteriner makbuzları ve GPS günlükleri bağışının sokaktan yuvaya yolculuğunu anlatır.",
      media: {
        poster: "/images/step-impact.avif",
        video: "/videos/step-impact.mp4",
        alt: "Etki panosu",
      },
    },
  ],
  stories: [
    {
      id: "mila",
      title: "Mila • 14 günde sokaktan kanepeye",
      copy: "Fethiye’de market önünde bulundu. Mikro bağışlar mamayı, aşıları ve Londra uçuşunu karşıladı.",
      stat: "14. Gün • Foster kanepesinde",
      media: {
        before: { poster: "/images/hero-rescue.png", alt: "Mila kurtarma öncesi" },
        after: { poster: "/images/story-mila.avif", alt: "Mila yeni yuvasında" },
        clip: { poster: "/images/story-mila.avif", video: "/videos/story-mila.mp4", alt: "Mila video klibi" },
      },
      ctaLabel: "Daha fazla kurtarmayı fonla",
      ctaHref: CTA_PRIMARY,
    },
    {
      id: "duman",
      title: "Duman • Acil tedaviden sahil koşularına",
      copy: "Antalya’da trafik kazası sonrası topluluk ameliyatı, rehabilitasyonu ve Brighton yolculuğunu finanse etti.",
      stat: "28. Gün • Sahiplendirmeye hazır",
      media: {
        before: { poster: "/images/hero-rescue.png", alt: "Duman tedavi öncesi" },
        after: { poster: "/images/story-duman.avif", alt: "Duman iyileştikten sonra" },
        clip: { poster: "/images/story-duman.avif", video: "/videos/story-duman.mp4", alt: "Duman video klibi" },
      },
      ctaLabel: "Bir öğün daha gönder",
      ctaHref: CTA_PRIMARY,
    },
  ],
  adoption: {
    eyebrow: "Sahiplen • Satın alma",
    headline: "Uçuşa hazır canlarımız yuvalarını bekliyor.",
    intro: "Saha ekibimiz her köpeği davranış notları, sağlık raporu ve DEFRA evrakıyla hazırlar. Sana uygun eşleşmeyi seç ya da uçuş fonuna destek ol.",
    cta: {
      adopt: { label: "Sahiplenme dosyalarını incele", href: "#adopt" },
      sponsor: { label: "Uçuş fonunu sponsorla", href: CTA_PRIMARY },
    },
    pets: [
      {
        id: "nova",
        name: "Nova",
        age: "2 yaş",
        breed: "Anadolu kırması",
        temperament: "Sakin",
        story: "Fethiye’de sahil kafesinde bulundu. Çocuklarla harika, tasma eğitimi tamam ve kafes yolculuğuna alışkın.",
        image: "/images/story-mila.avif",
        badge: "Uçuş hazır • 4 Ekim",
        medicalNotes: "Kalp kurdu negatif",
        adoptHref: "mailto:adoptions@angelshaven.org?subject=Nova%20i%C3%A7in%20sahiplenme",
        sponsorHref: CTA_PRIMARY,
      },
      {
        id: "argo",
        name: "Argo",
        age: "18 ay",
        breed: "Border collie kırması",
        temperament: "Oyunbaz",
        story: "İzmir’de sanayi bölgesinden kurtarıldı. Aktif aileleri seviyor, agility oyunlarında parlıyor.",
        image: "/images/story-duman.avif",
        badge: "Uçuş refakatçisi aranıyor • 12 Ekim",
        medicalNotes: "Eklem destek takviyesi kullanıyor",
        adoptHref: "mailto:adoptions@angelshaven.org?subject=Argo%20i%C3%A7in%20sahiplenme",
        sponsorHref: CTA_PRIMARY,
      },
      {
        id: "lale",
        name: "Lale",
        age: "3 yaş",
        breed: "Golden retriever kırması",
        temperament: "Arkadaş canlısı",
        story: "Pazar yerinin taşınması sonrası geride kaldı. İlk kez sahiplenen aileler için ideal, ev eğitimi tam.",
        image: "/images/story-after.png",
        badge: "Foster’dan sahiplendirme • Londra",
        medicalNotes: "Hassas mide",
        adoptHref: "mailto:adoptions@angelshaven.org?subject=Lale%20i%C3%A7in%20sahiplenme",
        sponsorHref: CTA_PRIMARY,
      },
    ],
    steps: [
      {
        id: "01",
        title: "Evin uygunluk formu",
        description: "Aile profilini, mevcut evcil dostlarını ve seyahat esnekliğini paylaş ki doğru eşleşmeyi önerelim.",
      },
      {
        id: "02",
        title: "Sanctuary canlı görüşmesi",
        description: "Davranış notları, veteriner raporu ve yolculuk planını barınaktan canlı aktarırız.",
      },
      {
        id: "03",
        title: "Uçuş + uyum desteği",
        description: "DEFRA uyumlu uçuşu ayarlarız, refakatçi göndeririz ve ilk 30 gün adaptasyon desteği veririz.",
      },
    ],
    fallback: {
      headline: "Şimdilik sahiplenemiyor musun?",
      copy: "Haftalık mama, tedavi ve uçuş kasasını sponsorla; yuvasını bekleyen canlar güvende kalsın.",
      donateLabel: "Mamayı sponsorla",
      donateHref: CTA_PRIMARY,
    },
  },
  sanctuary: {
    eyebrow: "Tülay'ın Çiftliği • İzmir kırsalı",
    headline: "Her kurtarma Avrupa'ya uçmadan önce burada nefes alıyor.",
    body: "Kurucumuz Tülay ve gönüllüler dört dönümlük çiftliği bir iyileşme köyüne dönüştürüyor; sokak canlarının yaralarını sarıyor, kaslarını güçlendiriyor ve gelecekteki ailelerine günlük videolar çekiyor.",
    highlight: "Gün doğumu kontrolleri, ilikli kemik sulu akşam mamaları ve WhatsApp videoları ilk günden ailelerle paylaşılır.",
    image: "/images/founder-tulay.png",
    quote: {
      text: "Onları yeniden koşarken görmek, gönderdiğiniz her £1'in tablo değil kalp atışı olduğunu kanıtlıyor.",
      name: "Tülay Arslan",
      role: "Kurucu & sanctuary sorumlusu",
    },
    pillars: [
      {
        id: "triage",
        title: "Gün doğumu triyajı",
        copy: "Yaralar temizlenir, ilaçlar verilir ve veteriner turu günün ilk saatinde planlanır.",
      },
      {
        id: "social",
        title: "Aile sosyalleşmesi",
        copy: "Mahalleli ve okul gönüllüleri çayırlarda saatler geçirir; ürkek patiler yeniden güvenmeyi öğrenir.",
      },
      {
        id: "travel",
        title: "Uçuş provası",
        copy: "DEFRA evrakları, kafes alıştırması ve havalimanı pratikleriyle yolculuk günü tanıdık gelir.",
      },
      {
        id: "updates",
        title: "Günlük güncellemeler",
        copy: "Kısa videolar ve kilometre taşları her akşam sponsor ve aile gruplarına düşer.",
      },
    ],
    stats: [
      { id: "rehab", value: "36", label: "Bu ay rehabilitasyon yataklarında" },
      { id: "escorts", value: "12", label: "AB yolculukları için gönüllü refakatçi" },
      { id: "acres", value: "4", label: "Dönüm ağaçlık iyileşme alanı" },
    ],
    cta: {
      primaryLabel: "Bir iyileşme gecesini sponsor et",
      primaryHref: CTA_PRIMARY,
      secondaryLabel: "Tülay'a erzak gönder",
      secondaryHref: "mailto:hello@angelshaven.org?subject=Sanctuary%20erzak%20deste%C4%9Fi",
      note: "Bağışların %100'ü mama, ilaç ve uçuş hazırlığa gider.",
    },
  },
  community: {
    eyebrow: "Topluluk • Şeffaflık",
    headline: "14.682 kişi Angels Haven'ı her gece canlı izliyor.",
    description: "Özel Facebook grubumuz; Tülay'ın çiftliğinden canlı yayınlar, veteriner faturaları, uçuş listeleri ve bağışçı soru-cevaplarını herkesten önce paylaşır.",
    fb: {
      members: "14.682 üye • günde 32 paylaşım",
      href: CTA_COMMUNITY,
      label: "Angels Haven Kurtarma Güncellemeleri",
      proof: "Her üye kimlik doğrulamasından geçer. Haftalık sabit gönderilerde defterler, faturalar ve refakatçi listeleri indirilebilir.",
    },
    highlights: [
      {
        id: "livestreams",
        title: "Her akşam canlı kontroller",
        copy: "Tülay, saat 21.00'de İzmir'den yayına girer; padok turu, ilaç çizelgesi ve mama hazırlığını gösterir.",
      },
      {
        id: "escorts",
        title: "Refakatçi koordinasyon hub'ı",
        copy: "Şablonlar, paket listeleri ve canlı havaalanı sohbetleri yeni refakatçilerin Londra, Berlin, Amsterdam uçuşlarına eşlik etmesini kolaylaştırır.",
      },
      {
        id: "ledger",
        title: "Açık defter başlıkları",
        copy: "Stripe ve PayPal dökümleri her ayın ilk günü; veteriner, mama ve taşıma kalemleriyle paylaşılır.",
      },
      {
        id: "alerts",
        title: "Hızlı müdahale uyarıları",
        copy: "Kritik kurtarmalarda @everyone etiketleri açılır; hedefler ortalama 90 dakikanın altında tamamlanır.",
      },
    ],
    stats: [
      { id: "escorts", value: "312", label: "Topluluk gönüllülerinin organize ettiği uçuş" },
      { id: "donors", value: "18.247", label: "Stripe & PayPal'da takip edilen düzenli bağışçı" },
      { id: "support", value: "%96", label: "24 saat içinde çözülen destek talebi" },
      { id: "streams", value: "365", label: "Son 12 ayda yayınlanan canlı yayın" },
    ],
    cta: {
      label: "Facebook grubuna katıl",
      href: CTA_COMMUNITY,
      secondaryLabel: "Son etki raporunu indir",
      secondaryHref: CTA_REPORT,
    },
  },
  testimonials: [
    {
      id: "amelia-tr",
      quote: "Yılda iki kez uçuşa refakat ediyorum—Heathrow'a inişimizi canlı izlediler ve vet kontrolü daha piste inmeden fonlandı.",
      name: "Amelia R., Londra",
      role: "Aylık bağışçı & foster",
      rating: 5,
      media: {
        poster: "/images/story-mila.avif",
        video: "/videos/story-mila.mp4",
        alt: "Amelia'nın uçuş deneyimi",
      },
    },
    {
      id: "umit-tr",
      quote: "Her makbuz birkaç saat içinde grupta. Açık defteri görünce bağışımı yıllık plana yükselttim.",
      name: "Ümit K., İzmir",
      role: "Sanctuary gönüllüsü",
      rating: 4.9,
      media: {
        poster: "/images/story-duman.avif",
        video: "/videos/story-duman.mp4",
        alt: "Ümit'in sanctuary anlatımı",
      },
    },
    {
      id: "niamh-tr",
      quote: "Kurumsal fonlarımızı Angels Haven'a ayırdık çünkü yönetişim paketleri ve canlı soru-cevaplar hiçbir boşluk bırakmıyor.",
      name: "Niamh F., Edinburgh",
      role: "Kurumsal sosyal sorumluluk lideri",
      rating: 4.8,
      media: {
        poster: "/images/step-impact.avif",
        video: "/videos/step-impact.mp4",
        alt: "Niamh'in CSR değerlendirmesi",
      },
    },
  ],
  securityBadges: [
    { id: "ssl", label: "TLS 1.3", description: "Cloudflare + Next.js ile 256-bit şifreleme" },
    { id: "pci", label: "PCI DSS", description: "Stripe ve PayPal Level 1 ödeme geçidi" },
    { id: "gdpr", label: "GDPR Uyumu", description: "Veri AB bölgelerinde saklanır, izin bazlı takip" },
    { id: "trust", label: "Şeffaflık Paneli", description: "Haftalık canlı defterler Facebook grubunda" },
  ],
  mediaRibbon: [
    { id: "guardian-feature", label: "Mikro bağışlarla uçuşlar", outlet: "The Guardian", href: "https://www.theguardian.com/uk" },
    { id: "bbc-late", label: "İstanbul gece görevleri", outlet: "BBC Radio London", href: "https://www.bbc.co.uk/sounds" },
    { id: "wired-panel", label: "Şeffaflık panelleri güveni geri getiriyor", outlet: "WIRED Impact", href: "https://www.wired.co.uk" },
  ],
  founder: {
    eyebrow: "Tülay ile tanış",
    headline: "Türk çiftliğini yaşam hattına dönüştüren havacılık lojistikçisi",
    paragraphs: [
      "Tülay Arslan, kıyı Türkiye ile İngiltere/AB arasındaki kurtarma koridorlarını resmileştirmek için on yıllık havayolu lojistik kariyerini geride bıraktı.",
      "Her akşam canlı yayınlarla yemek, tedavi ve ihracat evraklarını paylaşıyor; böylece bağışçılar hiçbir £1'in nereye gittiğini merak etmiyor.",
    ],
    credentials: [
      { id: "defra", label: "DEFRA Sertifikalı", detail: "2016'dan beri evcil hayvan seyahat uzmanı" },
      { id: "flight", label: "435 Uçuş", detail: "Refakatçi koordinasyonu" },
      { id: "ops", label: "Operasyon Kılavuzları", detail: "24 adımlı acil bakım protokolü" },
      { id: "languages", label: "Çift dilli", detail: "UK bağışçı + TR saha ekiplerini birleştiriyor" },
    ],
    stats: [
      { id: "dogs", value: "182", caption: "2021'den beri yuvalandırılan can" },
      { id: "livestreams", value: "365", caption: "Son 12 ayda yayınlanan canlı yayın" },
      { id: "volunteers", value: "94", caption: "Aktif sanctuary & refakatçi gönüllü" },
    ],
    image: "/images/founder-tulay.png",
    video: "/videos/hero-pack.mp4",
  },
  certificates: [
    {
      id: "charity-commission",
      title: "Charity Commission Kaydı",
      issuer: "Charity Commission for England & Wales",
      year: "2024",
      summary: "İngiltere hayır kurumu yasasına uygunluğu belgeleyen resmi kayıt.",
      href: "https://register-of-charities.charitycommission.gov.uk/charity-details/?regid=1204821",
    },
    {
      id: "hackney-cvs",
      title: "Hackney CVS Üyeliği",
      issuer: "Hackney Council for Voluntary Service",
      year: "2024",
      summary: "Yerel güvenlik ve yönetişim ağında doğrulanmış üyelik.",
      href: "https://hcvs.org.uk",
    },
    {
      id: "defra-license",
      title: "DEFRA Hayvan Taşıma Lisansı",
      issuer: "Department for Environment, Food & Rural Affairs",
      year: "2025",
      summary: "DEFRA TRACES kapsamında sınır ötesi taşıma yetkisi.",
      href: CTA_REPORT,
    },
    {
      id: "audit-letter",
      title: "Paws & Claws LLP FY23 Denetimi",
      issuer: "Paws & Claws LLP",
      year: "2024",
      summary: "Gelir, rezerv ve acil fon dağıtımlarına dair bağımsız doğrulama.",
      href: CTA_REPORT,
    },
    {
      id: "insurance",
      title: "Global Rescue Sigorta Poliçesi",
      issuer: "Global Rescue Underwriters",
      year: "2025",
      summary: "Refakatçi, sanctuary operasyonu ve kargo sorumluluğunu kapsayan poliçe.",
      href: CTA_REPORT,
    },
  ],
  donorWall: [
    { id: "amelia-donor", name: "Amelia R.", amount: 250, city: "Londra, UK", recurring: true, since: "2021" },
    { id: "umit-donor", name: "Ümit K.", amount: 140, city: "İzmir, TR", recurring: true, since: "2022" },
    { id: "morgan", name: "Morgan L.", amount: 500, city: "Manchester, UK", recurring: false, since: "2024" },
    { id: "melis", name: "Melis D.", amount: 75, city: "İstanbul, TR", recurring: true, since: "2023" },
  ],
  globalStats: [
    { id: "meals", label: "Servis edilen öğün", value: "72 bin", detail: "Fethiye, Dalyan, İzmir rotalarında kayıt altına alındı" },
    { id: "med", label: "Tıbbi vaka", value: "418", detail: "Acil ameliyatlar ortalama 6 saatte fonlandı" },
    { id: "escorts", label: "Gönüllü refakatçi", value: "312", detail: "Topluluk tarafından koordine edilen uçuşlar" },
    { id: "recurring", label: "Düzenli bağışçı", value: "18.247", detail: "Stripe + PayPal autopay destekçileri koridoru canlı tutuyor" },
  ],
  partners: [
    { id: "defra", name: "DEFRA", href: "https://www.gov.uk/government/organisations/department-for-environment-food-rural-affairs", description: "Pet travel uyum ortağı" },
    { id: "paws-claws", name: "Paws & Claws LLP", href: "https://example.com/paws-and-claws", description: "Bağımsız denetim firması" },
    { id: "global-rescue", name: "Global Rescue Underwriters", href: "https://example.com/global-rescue", description: "Taşıma sigortası" },
    { id: "hackney-cvs", name: "Hackney CVS", href: "https://hcvs.org.uk", description: "Güvenlik ağı" },
    { id: "vet-network", name: "TR Vet Ağı", href: "https://example.com/tr-vet", description: "18 klinikten oluşan tıbbi kolektif" },
  ],
  emergency: {
    title: "7 can uçağa hazır ama charter ücreti tamamlanmadı",
    description: "Her £120; DEFRA kafesleri, son vet kontrolleri ve gönüllü refakatçileri finanse eder. %100 olunca Pazar gecesi Heathrow hattı açılıyor.",
    goal: 8400,
    raised: 6240,
    currency: "£",
    dogsWaiting: 7,
    deadline: "Pazar 19:00 GMT",
    deadlineIso: "2025-02-16T19:00:00Z",
    ctaLabel: "Son adımı fonla",
    ctaHref: CTA_PRIMARY,
  },
  givingCalculator: {
    defaultAmount: 25,
    note: "Düzenli bağışçılar canlı makbuzlar, kafes manifestoları ve özel yayın uyarıları alır.",
    steps: [
      { amount: 8, label: "Mama & ilaç", description: "Ayda 30 öğün yüksek kalorili mama ve antibiyotikleri karşılar." },
      { amount: 25, label: "Uçuş payı", description: "Bir köpeğin DEFRA kafesi ve ihracat evrakının üçte birini sponsorlar." },
      { amount: 50, label: "Kurtarma koridoru", description: "Gece ambulansını acil toplama için hazır tutar." },
      { amount: 100, label: "Tam taşıma", description: "Sanctuary'den Heathrow'a kadar tüm yolculuğu ve refakatçiyi fonlar." },
    ],
  },
  impact24h: {
    headline: "Son 24 saatin etkisi",
    totalRaised: 2470,
    currency: "£",
    supporters: 186,
    flightsBooked: 3,
  },
  reels: [
    {
      id: "tulay-morning",
      title: "Tülay ile gün doğumu turu",
      description: "İlaç dozları, kemik suyu hazırlığı ve padok güncellemeleri çiftlikten canlı aktarılır.",
      media: { poster: "/images/story-mila.avif", video: "/videos/story-mila.mp4", alt: "Tülay barınakta köpeklerle ilgileniyor" },
    },
    {
      id: "flight-escort",
      title: "Heathrow öncesi refakat brifingi",
      description: "Gönüllüler kafes yüklemesi ve DEFRA evraklarını havaalanı öncesi prova eder.",
      media: { poster: "/images/story-duman.avif", video: "/videos/story-duman.mp4", alt: "Gönüllüler kafesleri hazırlıyor" },
    },
    {
      id: "adopter-update",
      title: "Londra'daki ilk kanepe gecesi",
      description: "Nova’nın yeni ailesi ilk geceyi ve vet kontrolü makbuzlarını paylaşıyor.",
      media: { poster: "/images/step-impact.avif", video: "/videos/step-impact.mp4", alt: "Adoptör aile güncelleme veriyor" },
    },
  ],
  bento: [
    {
      id: "meals",
      eyebrow: "Mama",
      title: "Ayda 2 ton mama",
      copy: "Fethiye, Dalyan ve İzmir barınaklarına her 14 günde GPS doğrulamalı sevkiyat yapılır.",
      ctaLabel: "Rota kayıtlarını gör",
      href: CTA_REPORT,
    },
    {
      id: "emergency",
      eyebrow: "Acil",
      title: "< 6 saatte yanıt",
      copy: "Uyarılar, veteriner bakımını ortalama altı saatin altında açan ops liderine düşer.",
      ctaLabel: "Makbuzları incele",
      href: CTA_REPORT,
    },
    {
      id: "sponsor",
      eyebrow: "Sponsor",
      title: "Bir pati sponsorluğu",
      copy: "Düzenli bağışçılar uçuş ve foster maliyetlerini karşılar; her ay bir köpeğe yolculuk hediye et.",
      ctaLabel: "Bugün sponsor ol",
      href: CTA_PRIMARY,
    },
    {
      id: "report",
      eyebrow: "Rapor",
      title: "Şeffaflık raporu",
      copy: "Günlük operasyon akışı, aylık raporlar ve uyum dosyaları gerçek zamanlı denetim sağlar.",
      ctaLabel: "Raporu indir",
      href: CTA_REPORT,
    },
  ],
  faq: [
    {
      question: "£1’in nereye gittiğini gerçekten görüyor muyum?",
      answer: "Evet. Her bağış yemek sayacı, veteriner makbuzu ve günlük etki videosunda anında görünür.",
    },
    {
      question: "Ödeme güvenli mi?",
      answer: "Stripe ve PayPal’ı TLS 1.3, Apple Pay, Google Pay ve Radar koruması ile kullanıyoruz—kart verisi sunucularımıza girmez.",
    },
    {
      question: "Düzenli bağışı durdurabilir miyim?",
      answer: "Makbuzundaki bağlantıdan tek dokunuşla durdurabilir ya da erteleyebilirsin; bekleme yok.",
    },
    {
      question: "Kurtarma ne kadar hızlı gerçekleşiyor?",
      answer: "Acil vakalar ortalama altı saatin altında fonlanır ve zaman çizelgesi adım adım paylaşılır.",
    },
    {
      question: "Vergi için makbuz alacak mıyım?",
      answer: "HMRC uyumlu makbuzlar anında e-postana düşer ve aylık döküm oluşturur.",
    },
    {
      question: "Bağıştan sonra ne olur?",
      answer: "Özel etki akışına katılır, perde arkası içerikleri izler ve istersen uçuş gönüllüsü olursun.",
    },
  ],
  final: {
    eyebrow: "Bir sonraki kurtarmaya hazır mısın?",
    headline: "Bugün bir köpeği daha güvende tut.",
    body: "£1; mamayı, tedaviyi ve yolculuğu tetikler. Her ay 2 ton yardımı hareket ettiren bağışçılara katıl.",
    ctaLabel: "£1 Bugün Besler",
    secondaryLabel: "Facebook grubuna katıl",
    secondaryHref: CTA_COMMUNITY,
    donateHref: CTA_PRIMARY,
  },
  trust: {
    headline: "Kaydı, denetimi ve sahadaki ekibiyle gerçek bir kurum.",
    copy: "Angels Haven, İngiltere’deki yönetim kurulu ve Türkiye’deki saha ortaklarıyla çift bölgeli çalışır. Her belge, sertifika ve güvenlik kontrolü bağışçılarla paylaşılır.",
    signals: [
      {
        id: "registration",
        title: "Charity Commission • #1204821",
        detail: "12 Ocak 2021’den beri İngiltere & Galler kayıtlı hayır kurumu.",
        proof: "2024’te Charity Commission kaydında doğrulandı.",
      },
      {
        id: "audit",
        title: "Paws & Claws LLP bağımsız denetimi",
        detail: "UK idari giderleri, TR saha harcamaları ve acil rezervleri yıllık raporda.",
        proof: "2023 mali yılı denetimi 08 Şubat 2024’te sıfır bulgu ile tamamlandı.",
      },
      {
        id: "safeguard",
        title: "Tam güvenlik ve DBS taraması",
        detail: "Tüm gönüllüler, taşıma ve foster ekipleri 12 ayda bir yeniden taranır.",
        proof: "Uyum günlüğü bağışçı şeffaflık panelinde herkese açık.",
      },
      {
        id: "community-proof",
        title: "Facebook grubunda canlı defterler",
        detail: "Sabitlenen şeffaflık gönderileri aylık XLS dökümleri, canlı yayın arşivi ve refakatçi listelerini içerir.",
        proof: "Facebook grubundaki Şeffaflık rehberine (Modül 01–03) göz atın.",
      },
    ],
    metrics: [
      { id: "meals", label: "Aylık öğün", value: "2.184", caption: "Fethiye, Dalyan, İzmir güzergahları GPS kayıtlı." },
      { id: "flights", label: "Refakat edilen uçuş", value: "312", caption: "Topluluk hub'ında gönüllüler tarafından koordine edildi." },
      { id: "donors", label: "Düzenli bağışçı", value: "18.247", caption: "Stripe + PayPal autopay destekçileri üç aylık kontrol altında." },
      { id: "rating", label: "Şeffaflık puanı", value: "4.9 / 5", caption: "Trustpilot + Google ortalaması." },
    ],
    accreditations: [
      { id: "charity-commission", label: "UK Charity Commission", description: "Resmi kayıt", href: "https://register-of-charities.charitycommission.gov.uk" },
      { id: "hcvo", label: "Hackney CVS Üyesi", description: "Yerel STK ağı", href: "https://hcvs.org.uk" },
      { id: "defra", label: "DEFRA Taşıma Lisansı", description: "Evcil hayvan taşımacılığı uyumu" },
    ],
    reviews: [
      { id: "review-ayse", quote: "Bağış yaptıktan 5 dakika sonra veteriner faturası ve rota bildirimi geldi. Şeffaflıkta rakipsizler.", name: "Ayşe K., Londra", role: "2022’den beri aylık bağışçı" },
      { id: "review-levent", quote: "İki köpeği Heathrow’a biz eskort ettik; süreç ve refah standartları kusursuzdu.", name: "Levent A., İzmir", role: "Uçuş gönüllüsü" },
      { id: "review-elif", quote: "Kurumsal sosyal sorumluluk programımız bu şeffaflık paketine bayıldı—hazır dokümanla geldiler.", name: "Elif R., İstanbul", role: "Kurumsal iş birlikleri" },
      { id: "review-hasan", quote: "Acil vakalar saatler içinde fonlanıyor; Duman’ın bacağını topluluk kurtardı.", name: "Hasan T., Antalya", role: "Partner veteriner" },
    ],
    team: [
      { id: "tulay", name: "Tülay Demir", role: "Kurucu & Saha Operasyonları", bio: "Havacılık lojistiğinden gelen deneyimiyle Muğla genelinde kurtarma ve tedaviyi koordine ediyor." },
      { id: "aaron", name: "Aaron Blake", role: "UK Programları & Uyum", bio: "Eski Charity Commission analisti; tüm rapor ve Gift Aid süreçlerini yönetiyor." },
      { id: "seda", name: "Seda Yıldız", role: "Veteriner Ağları", bio: "18 kliniklik ağı yönetip AB seyahat standartlarına uygun bakımı garanti ediyor." },
      { id: "leila", name: "Leila Khan", role: "Bağışçı Deneyimi", bio: "Canlı yayınları, WhatsApp güncellemelerini ve şeffaflık panelini yürütüyor." },
    ],
    media: [
      { id: "guardian", outlet: "The Guardian", href: "https://www.theguardian.com/uk", date: "Mart 2024", headline: "Mikro bağışlarla Türkiye’den uçan kurtarma uçuşları" },
      { id: "bbc", outlet: "BBC Radio London", href: "https://www.bbc.co.uk/sounds", date: "Ocak 2024", headline: "Angels Haven’ın İstanbul gece görevleri" },
      { id: "wired", outlet: "WIRED Impact", href: "https://www.wired.co.uk", date: "Kasım 2023", headline: "Şeffaflık panelleri bağışçı güvenini nasıl geri getiriyor" },
    ],
    contact: [
      { label: "E-posta", value: "verify@angelshaven.org", href: "mailto:verify@angelshaven.org" },
      { label: "Telefon", value: "+44 20 7946 0958", href: "tel:+442079460958" },
      { label: "Merkez", value: "18 Market Walk, Islington, London N1 7SR" },
      { label: "TR Operasyon", value: "Calis Mah. 112. Sokak No:4, Fethiye / Muğla" },
      { label: "Facebook", value: "Kurtarma Güncellemeleri", href: CTA_COMMUNITY },
    ],
    proofDocument: {
      label: "Şeffaflık paketini indir",
      href: CTA_REPORT,
      description: "Kayıt sertifikaları, güvenlik politikası, taşıma sigortası ve 2023 denetim mektubu.",
    },
  },
  footer: {
    registration: "Charity Commission (England & Wales) No. 1204821",
    address: "18 Market Walk, Islington, London N1 7SR • Operasyon üssü: Calis Mah. 112. Sokak No:4, Fethiye / Muğla",
    email: "destek@angelshaven.org",
    phone: "+44 20 7946 0958",
    hours: "Çağrı hattı: Pzt–Cmt 08:00–20:00 GMT",
    socials: [
      { label: "Facebook Grubu", href: CTA_COMMUNITY },
      { label: "Instagram", href: "https://instagram.com/angelshavenpaws" },
      { label: "YouTube", href: "https://youtube.com/@angelshaven" },
      { label: "TikTok", href: "https://www.tiktok.com/@angelshaven" },
      { label: "LinkedIn", href: "https://linkedin.com/company/angelshaven" },
    ],
    policies: [
      { label: "Gizlilik", href: "/privacy" },
      { label: "Koşullar", href: "/terms" },
      { label: "Etki raporu", href: CTA_REPORT },
    ],
    legal: [
      { label: "Hakkımızda", href: "/about" },
      { label: "Şeffaflık", href: "/transparency" },
      { label: "Basın", href: "/press" },
    ],
  },
};

export default function HomeTR() {
  return <Landing content={TR_CONTENT} />;
}
